---
# tasks file for roles/grafana

- name: Download grafana
  ansible.builtin.get_url:
    url: "{{ grafana_download_url }}"
    dest: "{{ grafana_destination_path }}"

- name: Install grafana
  ansible.builtin.apt:
    deb: "{{ grafana_destination_path }}"

- name: Start service grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true



