---
# tasks file for roles/exporters_filebeat
 - name: Create node exporter user
   ansible.builtin.user:
     name: "{{ node_exporter_user }}"
     shell: /usr/sbin/nologin
     system: true
     create_home: false

 - name: Download and unzip exporter
   ansible.builtin.unarchive:
     src: "{{ node_exporter_download_url }}"
     dest: /tmp/
     remote_src: yes

 - name: Move the binary file
   ansible.builtin.copy:
     src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
     dest: "{{ node_exporter_bin }}"
     owner: "{{ node_exporter_user }}"
     group: "{{ node_exporter_group }}"
     mode: 0755
     remote_src: yes

 - name: Create service
   ansible.builtin.template:
     src: node_exporter.service.j2
     dest: /etc/systemd/system/node_exporter.service
     owner: root
     group: root
     mode: 0644
   notify: Reload daemon and restart node exporter

 - name: Start and enable service
   ansible.builtin.systemd:
     name: node_exporter
     state: started
     enabled: true



