---
# tasks file for roles/prometheus
 - name: Create prometheus system user
   ansible.builtin.user:
     name: "{{ prometheus_user }}"
     shell: /usr/sbin/nologin
     system: true
     create_home: false

 - name: Create directories
   ansible.builtin.file:
     path: "{{ item }}"
     state: directory
     owner: "{{ prometheus_user }}"
     group: "{{ prometheus_group }}"
     mode: 0755
   with_items:
       - "{{ prometheus_config_dir }}"
       - "{{ prometheus_db_dir }}"

 - name: Download and unzip prometheus
   ansible.builtin.unarchive:
     src: "{{ prometheus_download_url }}"
     dest: /tmp/
     remote_src: yes

 - name: Copy the binary files
   ansible.builtin.copy:
     src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
     dest: "{{ prometheus_bin_dir }}/{{ item }}"
     owner: "{{ prometheus_user }}"
     group: "{{ prometheus_group }}"
     mode: 0755
     remote_src: yes
   with_items:
      - prometheus
      - promtool

 - name: Copy console files
   ansible.builtin.copy:
     src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
     dest: "{{ prometheus_config_dir }}/{{ item}}/"
     owner: "{{ prometheus_user }}"
     group: "{{prometheus_group}}"
     mode: 0644
     remote_src: yes
   with_items:
     - console_libraries
     - consoles

 - name: Configuration prometheus
   ansible.builtin.template:
     src: prometheus.yml.j2
     dest: "{{ prometheus_config_dir }}/prometheus.yml"
     owner: "{{ prometheus_user }}"
     group: "{{prometheus_group }}"
     mode: 0644
   notify: Reload prometheus

 - name: Service prometheus
   ansible.builtin.template:
     src: prometheus.service.j2
     dest: "{{ prometheus_service_dir }}"
     owner: "{{ prometheus_user }}"
     group: "{{ prometheus_group }}"
     mode: 0644
   notify: Restart prometheus

 - name: Start and enable prometheus
   ansible.builtin.systemd:
     name: prometheus
     state: started
     enabled: true





