---
# tasks file for nginx
 - name: Install epel-release
   yum:
     name: epel-release
     state: present

 - name: Install nginx
   yum:
     name: nginx
     state: present

 - name: Start nginx
   systemd:
     name: nginx
     state: started
     enabled: true

 - name: Create configuration
   template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf
     owner: root
     group: root
     mode: 0644
   notify: restart nginx

 - name: Insert content
   copy:
     src: index.html
     dest: /usr/share/nginx/html
   notify: restart nginx

   
